require("sussyspt/rendering/tabs/online")
require("sussyspt/rendering/tabs/qol")
require("sussyspt/rendering/tabs/singleplayer")
require("sussyspt/rendering/tabs/quickActions")
require("sussyspt/rendering/tabs/config")
require("sussyspt/rendering/tabs/dev")
