name: Bug Report
description: "Submit a Bug Report"
title: "[Bug] "
labels: bug
body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: Provide a clear and concise description of what went wrong.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Describe the steps to reproduce the behavior.
      placeholder: |
        1. Do this
        2. Do that
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: Specify what you expected to happen if the bug didn't exist.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Logs and/or Screenshots (if applicable)
      description: |
        Include the cout.log file from YimMenu.
        You can find it at "%appdata%/YimMenu/cout.log".
        Tip: You can drag and drop files here for upload.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional info
      description: |
        Include the cout.log file from YimMenu.
        You can find it at "%appdata%/YimMenu/cout.log".
        Tip: You can drag and drop files here for upload.
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Checklist
      options:
        - label: The issue exists using the latest version (or was not fixed)
          required: true
        - label: The issue only occurs with scripts from this repository loaded
          required: false
