name: Bug Report
description: 'Submit a Bug Report'
title: '[Bug] '
labels: bug
body:
  - type: textarea
    attributes:
      label: Bug Description
      description: Provide a clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Describe the steps to reproduce the issue.
      placeholder: |
        1. Do this
        2. Do that
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: Specify what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Logs and Screenshots (if applicable)
      description: |
        Include the cout.log file from YimMenu.
        You can find it here: '%appdata%/YimMenu/cout.log'.
        Tip: You can drag and drop files here for upload.
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Version
      options:
        - label: The issue exists in the latest version
          required: true
  - type: checkboxes
    attributes:
      label: Testing Without Scripts
      options:
        - label: The issue does not occur without any additional scripts
          required: false
